POST http://localhost:8080/local/checker/execute
Content-Type: application/json
{
  "url": "http://www.baidu.com/abc",
  "headerList": [
    {
      "name": "origin",
      "value": "http://www.baidu1.com"
    }
  ]
}
